name: media_picker
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  photo_manager: ^3.6.2
  flutter_bloc: ^8.1.6
  injectable: ^2.5.0
  get_it: ^8.0.2
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  infinite_scroll_pagination: ^4.1.0
  animated_custom_dropdown: ^3.1.1
  equatable: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  build_runner: ^2.4.13

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  
  
